BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE ${otp_table_name} (
            USERNAME VARCHAR2(255) NOT NULL,
            OTP VARCHAR2(16) NOT NULL,
            OTP_TYPE VARCHAR2(50) NOT NULL,
            METADATA CLOB,
            EXPIRY_TIME TIMESTAMP NOT NULL,
            DELIVERY_METHOD VARCHAR2(50),
            DELIVERY_STATUS VARCHAR2(255),
            IS_USED NUMBER(1) DEFAULT 0 NOT NULL,
            PRIMARY KEY (USERNAME, OTP, OTP_TYPE)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

