CREATE TABLE IF NOT EXISTS OTP_STORE (
    USERNAME VARCHAR(255) NOT NULL,
    OTP VARCHAR(16) NOT NULL,
    OTP_TYPE VARCHAR(64) NOT NULL,
    METADATA TEXT NULL,
    EXPIRY_TIME TIMESTAMP NOT NULL,
    DELIVERY_METHOD VARCHAR(255) NULL,
    DELIVERY_STATUS VARCHAR(255) NULL,
    IS_USED BOOLEAN NOT NULL DEFAULT FALSE
);