IF OBJECT_ID('${otp_table_name}', 'U') IS NULL
BEGIN
    CREATE TABLE ${otp_table_name} (
        USERNAME VARCHAR(255) NOT NULL,
        OTP VARCHAR(16) NOT NULL,
        OTP_TYPE VARCHAR(50) NOT NULL,
        METADATA NVARCHAR(MAX) NULL,
        EXPIRY_TIME DATETIME2 NOT NULL,
        DELIVERY_METHOD VARCHAR(50) NULL,
        DELIVERY_STATUS VARCHAR(255) NULL,
        IS_USED BIT NOT NULL DEFAULT 0,
        PRIMARY KEY (USERNAME, OTP, OTP_TYPE)
    );
END;

