CREATE TABLE IF NOT EXISTS ${otp_table_name} (
    USERNAME VARCHAR(255) NOT NULL,
    OTP VARCHAR(16) NOT NULL,
    OTP_TYPE VARCHAR(50) NOT NULL,
    METADATA TEXT,
    EXPIRY_TIME TIMESTAMP NOT NULL,
    DELIVERY_METHOD VARCHAR(50),
    DELIVERY_STATUS VARCHAR(255),
    IS_USED BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (USERNAME, OTP, OTP_TYPE)
);

